# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: ubuntu_16_04
    displayName: 'Build - Ubuntu 16.04'
    continueOnError: false
    pool:
      vmImage: 'Ubuntu 16.04'
    workspace:
      clean: all
    steps:
      - script: |
          ./build-mbedtls.sh
        workingDirectory: utility/install-deps
      - script: |
          mkdir build
      - task: CMake@1
      - script: |
          cmake -DMBEDTLS_ROOT_DIR=$(Build.SourcesDirectory)/utility/install-deps/tmp/mbedtls/build -DOATPP_MODULES_LOCATION=EXTERNAL ..
          make
        displayName: 'CMake'
        workingDirectory: build
      - script: |
          ./module-tests
        displayName: 'Test'
        workingDirectory: build/test
#  - job: macOS
#    displayName: 'Build - macOS'
#    continueOnError: false
#    pool:
#      vmImage: 'macOS-10.14'
#    workspace:
#      clean: all
#    steps:
#      - script: |
#          mkdir build
#      - task: CMake@1
#      - script: |
#          cmake -DCMAKE_BUILD_TYPE=Release ..
#          make
#        displayName: 'CMake'
#        workingDirectory: build
#      - script: |
#          make test ARGS="-V"
#        displayName: 'Test'
#        workingDirectory: build
